### ISSUE TITLE
Depend on an old version of LibSSL

### ISSUE THREAD

**Issue by nfrankel** [benbalter/jekyll-include-cache#15]
When launching `jekyll`, I have this stack trace:

```
bundler: failed to load command: jekyll (/Users/nico/.rbenv/versions/2.6.3/bin/jekyll)
LoadError: dlopen(/Users/nico/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/md5.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/nico/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/md5.bundle
  Reason: image not found - /Users/nico/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin18/digest/md5.bundle
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-include-cache-0.2.0/lib/jekyll-include-cache/tag.rb:3:in `require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-include-cache-0.2.0/lib/jekyll-include-cache/tag.rb:3:in `<top (required)>'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-include-cache-0.2.0/lib/jekyll-include-cache.rb:24:in `require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-include-cache-0.2.0/lib/jekyll-include-cache.rb:24:in `<top (required)>'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
  /Users/nico/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
  /Users/nico/.rbenv/versions/2.6.3/bin/jekyll:23:in `load'
  /Users/nico/.rbenv/versions/2.6.3/bin/jekyll:23:in `<top (required)>'
```

1. Install Jenkins 4.0.0
2. Install Bundler 2.0.2
3. Configure Gemfile to use the plugin:
    ```
    gem 'jekyll-include-cache'
    ```
4. Launch Jenkins. It doesn't start and the above stack trace is displayed.

Is there any way to update the dependency to the latest LibSSL (1.1)?

```
$ ls /usr/local/opt/openssl/lib/

engines-1.1         libcrypto.1.1.dylib libcrypto.a         libcrypto.dylib     libssl.1.1.dylib    libssl.a            libssl.dylib        pkgconfig
```

**Comment by nfrankel** [comment]
Sorry, my Ruby-Fu is close to 0. It was the Ruby version the culprit. Once I upgraded, everything went fine.
